name: Deploy Eurocard (Self-Hosted Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to local folder
        run: |
          sudo rm -rf /var/www/eurocard/*
          sudo cp -r * /var/www/eurocard/
          sudo systemctl reload nginx
